//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CeeeVolunteeringOneDayChallenge
    {
        public CeeeVolunteeringOneDayChallenge()
        {
            this.CeeeJobDescriptions = new HashSet<CeeeJobDescription>();
        }
    
        public int VolunteeringJobId { get; set; }
        public string ProjectEventTitle { get; set; }
        public string Location { get; set; }
        public string When { get; set; }
        public string MeetingTime { get; set; }
        public string FinishingTime { get; set; }
        public string MeetingPoint { get; set; }
        public string WhatWillBeDoing { get; set; }
        public string ExperienceNeeded { get; set; }
        public Nullable<bool> IsCordinatedByUniversity { get; set; }
        public byte[] RiskAssesmentFile { get; set; }
        public byte[] SessionPlanFile { get; set; }
        public byte[] BudgetPlanFile { get; set; }
        public Nullable<bool> HasInsuranceLiability { get; set; }
        public Nullable<bool> HasCarriedOutRiskAssesment { get; set; }
        public Nullable<int> VolunteeringTypeId { get; set; }
        public string OpportunityTypes { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string AlternateEmail { get; set; }
        public string OrganisationType { get; set; }
    
        public virtual CeeeVolunteeringType CeeeVolunteeringType { get; set; }
        public virtual ICollection<CeeeJobDescription> CeeeJobDescriptions { get; set; }
    }
}
