//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CeeeClientAttribute
    {
        public int ClientAttributeID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string LandlineNumber { get; set; }
        public string MobileNumber { get; set; }
        public string OrganisationWebsite { get; set; }
        public string CompanySize { get; set; }
        public string HowHeard { get; set; }
        public string Title { get; set; }
        public string JobTitle { get; set; }
    
        public virtual CeeeUser CeeeUser { get; set; }
        public virtual Client Client { get; set; }
    }
}
