//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CeeeOpportunityType
    {
        public int OpportunityType { get; set; }
        public string OpportunityName { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual CeeeUser CeeeUser { get; set; }
    }
}
