//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CeeeJobDescription
    {
        public int JobDescriptionID { get; set; }
        public Nullable<int> JobTypeID { get; set; }
        public Nullable<int> JobCategoryID { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string SalaryPeriod { get; set; }
        public string HowEmployeeApproaches { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<decimal> NoOfHoursPerWeek { get; set; }
        public Nullable<bool> IsVolunteering { get; set; }
        public Nullable<int> VolunteeringTypeID { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> OneDayVolunteeringID { get; set; }
        public Nullable<int> VolunteeringPlacmentID { get; set; }
        public Nullable<int> JobContractTypeID { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual CeeeJobContractType CeeeJobContractType { get; set; }
        public virtual CeeeVolunteeringOneDayChallenge CeeeVolunteeringOneDayChallenge { get; set; }
        public virtual Job Job { get; set; }
        public virtual CeeeJobType CeeeJobType { get; set; }
        public virtual CeeeVolunteeringPlacement CeeeVolunteeringPlacement { get; set; }
    }
}
