//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CeeeVolunteeringType
    {
        public CeeeVolunteeringType()
        {
            this.CeeeVolunteeringOneDayChallenges = new HashSet<CeeeVolunteeringOneDayChallenge>();
            this.CeeeVolunteeringPlacements = new HashSet<CeeeVolunteeringPlacement>();
        }
    
        public int VolunteeringTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CeeeVolunteeringOneDayChallenge> CeeeVolunteeringOneDayChallenges { get; set; }
        public virtual ICollection<CeeeVolunteeringPlacement> CeeeVolunteeringPlacements { get; set; }
    }
}
