//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProNetTestEntities : DbContext
    {
        public ProNetTestEntities()
            : base("name=ProNetTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> Clients { get; set; }
        public DbSet<DocumentContent> DocumentContents { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<DocumentStatu> DocumentStatus { get; set; }
        public DbSet<EmploymentType> EmploymentTypes { get; set; }
        public DbSet<JobAttribute> JobAttributes { get; set; }
        public DbSet<JobCategory> JobCategories { get; set; }
        public DbSet<JobDocument> JobDocuments { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<Object> Objects { get; set; }
        public DbSet<ObjectType> ObjectTypes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<CeeeOpportunityType> CeeeOpportunityTypes { get; set; }
        public DbSet<ClientContact> ClientContacts { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<CeeeClientAttribute> CeeeClientAttributes { get; set; }
        public DbSet<CeeeJobType> CeeeJobTypes { get; set; }
        public DbSet<CeeeUser> CeeeUsers { get; set; }
        public DbSet<CeeeVolunteeringOneDayChallenge> CeeeVolunteeringOneDayChallenges { get; set; }
        public DbSet<CeeeVolunteeringPlacement> CeeeVolunteeringPlacements { get; set; }
        public DbSet<CeeeVolunteeringType> CeeeVolunteeringTypes { get; set; }
        public DbSet<CeeeJobContractType> CeeeJobContractTypes { get; set; }
        public DbSet<CeeeJobDescription> CeeeJobDescriptions { get; set; }
    }
}
