//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CeeeVolunteeringPlacement
    {
        public CeeeVolunteeringPlacement()
        {
            this.CeeeJobDescriptions = new HashSet<CeeeJobDescription>();
        }
    
        public int VolunteeringJobID { get; set; }
        public string RoleTitle { get; set; }
        public string Location { get; set; }
        public string DayTimeRequired { get; set; }
        public string DurationNeeded { get; set; }
        public string SkillsRequired { get; set; }
        public string TrainingDetails { get; set; }
        public string ApplicationMethod { get; set; }
        public byte[] ApplicationForm { get; set; }
        public string HowToPostApplication { get; set; }
        public byte[] RoleDescriptionFile { get; set; }
        public Nullable<bool> HasLiabilityInsurance { get; set; }
        public Nullable<bool> HasCarriedOutRiskAssesment { get; set; }
        public Nullable<int> NumberOfPositions { get; set; }
        public Nullable<int> VolunteeringTypeID { get; set; }
        public string OpportunityTypes { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string AlternateEmail { get; set; }
        public string OrganisationType { get; set; }
        public string AboutOrganisation { get; set; }
    
        public virtual CeeeVolunteeringType CeeeVolunteeringType { get; set; }
        public virtual ICollection<CeeeJobDescription> CeeeJobDescriptions { get; set; }
    }
}
