//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Jobs = new HashSet<Job>();
            this.Jobs1 = new HashSet<Job>();
            this.ClientContacts = new HashSet<ClientContact>();
            this.CeeeUsers = new HashSet<CeeeUser>();
        }
    
        public int ClientID { get; set; }
        public string Company { get; set; }
        public string OurReference { get; set; }
        public string Notes { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<decimal> DefaultTermPerc { get; set; }
        public Nullable<int> PrimaryEmailAddressPhoneId { get; set; }
        public Nullable<int> CanvassPeriodValueId { get; set; }
        public Nullable<int> InvoiceContactId { get; set; }
        public Nullable<int> InvoiceAddressId { get; set; }
        public string VatNo { get; set; }
        public string RegNo { get; set; }
        public int CreatedUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] UpdatedTimestamp { get; set; }
        public Nullable<int> CreditLimit { get; set; }
        public Nullable<System.DateTime> CreditReviewDate { get; set; }
        public Nullable<bool> NoVAT { get; set; }
        public Nullable<bool> CreditCheck { get; set; }
        public Nullable<bool> CreditStop { get; set; }
        public string CreditNotes { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<Job> Jobs1 { get; set; }
        public virtual Location Location { get; set; }
        public virtual Object Object { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<ClientContact> ClientContacts { get; set; }
        public virtual ClientContact ClientContact { get; set; }
        public virtual CeeeClientAttribute CeeeClientAttribute { get; set; }
        public virtual ICollection<CeeeUser> CeeeUsers { get; set; }
    }
}
