//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientContact
    {
        public ClientContact()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int ClientContactId { get; set; }
        public int ClientId { get; set; }
        public int ContactPersonId { get; set; }
        public int ContactTypeId { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> PositionValueId { get; set; }
        public string Department { get; set; }
        public Nullable<int> PriorityValueId { get; set; }
        public Nullable<int> PrimaryEmailAddressPhoneId { get; set; }
        public Nullable<System.DateTime> EmploymentStartDate { get; set; }
        public Nullable<System.DateTime> EmploymentEndDate { get; set; }
        public Nullable<int> EmploymentTypeId { get; set; }
        public Nullable<int> PlacementId { get; set; }
        public Nullable<int> ReportsToPersonId { get; set; }
        public Nullable<int> CanvassPeriodValueId { get; set; }
        public string HasLeft { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public int CreatedUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] UpdatedTimestamp { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual EmploymentType EmploymentType { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
    }
}
