//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentContent
    {
        public int DocumentId { get; set; }
        public byte[] Document { get; set; }
        public string FileExtension { get; set; }
        public int CreatedUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public byte[] UpdatedTimestamp { get; set; }
        public bool IsStoredExternally { get; set; }
    
        public virtual Document Document1 { get; set; }
    }
}
