//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.JobDocuments = new HashSet<JobDocument>();
        }
    
        public int DocumentID { get; set; }
        public string Description { get; set; }
        public Nullable<int> NotebookItemId { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public string Publishable { get; set; }
        public string Incoming { get; set; }
        public Nullable<int> DocumentStatusId { get; set; }
        public int CreatedUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] UpdatedTimestamp { get; set; }
        public string ExternalEditorOnly { get; set; }
        public bool Protected { get; set; }
        public string SourceDoc { get; set; }
    
        public virtual DocumentContent DocumentContent { get; set; }
        public virtual DocumentStatu DocumentStatu { get; set; }
        public virtual ICollection<JobDocument> JobDocuments { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
