//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.JobAttributes = new HashSet<JobAttribute>();
            this.JobDocuments = new HashSet<JobDocument>();
            this.CeeeJobDescriptions = new HashSet<CeeeJobDescription>();
        }
    
        public int JobId { get; set; }
        public int ClientId { get; set; }
        public int SectorId { get; set; }
        public string JobRefNo { get; set; }
        public Nullable<int> ClientContactId { get; set; }
        public Nullable<int> PositionAttributeId { get; set; }
        public string PosCode { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> AreaAttributeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> EmploymentTypeId { get; set; }
        public Nullable<decimal> MinBasic { get; set; }
        public Nullable<decimal> MaxBasic { get; set; }
        public Nullable<decimal> MinPackage { get; set; }
        public Nullable<decimal> MaxPackage { get; set; }
        public Nullable<int> MinAge { get; set; }
        public Nullable<int> MaxAge { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string Notes { get; set; }
        public string InterviewAddress { get; set; }
        public string AppIntInfo { get; set; }
        public Nullable<decimal> HoursPerWeek { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string Published { get; set; }
        public Nullable<int> PublishedJobCategoryId { get; set; }
        public string PublishedJobDescription { get; set; }
        public string Archived { get; set; }
        public string CVKeyWord { get; set; }
        public int CreatedUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] UpdatedTimestamp { get; set; }
        public string WorkAddress { get; set; }
        public string PurchaseOrderNo { get; set; }
        public Nullable<int> NoOfPlaces { get; set; }
        public Nullable<int> InvoiceContactId { get; set; }
        public Nullable<decimal> CommissionPerc { get; set; }
        public Nullable<decimal> PlacementFee { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<bool> Tier2ReleaseHold { get; set; }
        public Nullable<bool> Retainer { get; set; }
        public Nullable<decimal> TotalRetainerFee { get; set; }
        public Nullable<int> ClientHirerLegalEntityId { get; set; }
        public Nullable<int> JobTemplateId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual ICollection<JobAttribute> JobAttributes { get; set; }
        public virtual ICollection<JobDocument> JobDocuments { get; set; }
        public virtual ICollection<CeeeJobDescription> CeeeJobDescriptions { get; set; }
    }
}
