//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobAttribute
    {
        public int JobAttributeId { get; set; }
        public int JobId { get; set; }
        public int AttributeId { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<int> Set { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Notes { get; set; }
        public int CreatedUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] UpdatedTimestamp { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
