//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDocument
    {
        public int JobDocumentId { get; set; }
        public int JobId { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> JobDocDefinitionId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public string Completed { get; set; }
        public int CreatedUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public byte[] UpdatedTimestamp { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Job Job { get; set; }
    }
}
