//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEEEDataAccess.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.ClientContacts = new HashSet<ClientContact>();
            this.ClientContacts1 = new HashSet<ClientContact>();
        }
    
        public int PersonID { get; set; }
        public string PersonName { get; set; }
        public string Surname { get; set; }
        public Nullable<int> TitleValueId { get; set; }
        public string Salutation { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<int> GenderValueId { get; set; }
        public Nullable<int> MaritalStatusValueId { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public string Notes { get; set; }
        public byte[] Photograph { get; set; }
        public int CreatedUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte[] UpdatedTimestamp { get; set; }
    
        public virtual ICollection<ClientContact> ClientContacts { get; set; }
        public virtual ICollection<ClientContact> ClientContacts1 { get; set; }
        public virtual Object Object { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
